version: "3"

networks:
  main:
    name: main

services:
  bot:
    container_name: beira
    networks:
      - main
    depends_on:
      - database
      - lavalink
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json

  database:
    container_name: discord-beira-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      interval: 1s
      retries: 10
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      timeout: 5s
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G # set Java options here
      - SERVER_PORT=2333 # set lavalink server port
      - LAVALINK_SERVER_PASSWORD=gloater-body-galvanize # set password for lavalink
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml # mount application.yml from the same directory or use environment variables
      - ./plugins/:/opt/Lavalink/plugins/ # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
    networks:
      - main
    expose:
      - 2333 # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
    ports:
      - 2333:2333 # you only need this if you want to make your lavalink accessible from outside of containers

volumes:
  pgdata: