name: Type Coverage and Linting

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    name: "Type Coverage and Linting @ ${{ matrix.python-version }}"
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup CPython @ ${{ matrix.python-version }}"
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install Python deps @ ${{ matrix.python-version }}"
        id: install-deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -U -r requirements.txt
    
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: "Run Pyright @ ${{ matrix.python-version }}"
        uses: jakebailey/pyright-action@v1

      - name: Run Ruff
        uses: chartboost/ruff-action@v1

      - name: Run Black
        uses: psf/black@stable